version: "3.7"

services:
  server:
    build:
      context: "."
      target: base
    environment:
      SERVER_DATABASE_NAME: test
      PRISMA_DATABASE_URL: file:./test.db
    ports:
      - 9999:80
    volumes:
      - ./src:/var/www/src
      - ./package.json:/var/www/package.json
    networks:
      - test_vm
    # depends_on:
    #   - database

  # database:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_PORT=3306
  #   volumes:
  #     - database:/var/lib/mysql
  #   expose:
  #     - 3307
  #   ports:
  #     - 3307:3306
  #   networks:
  #     - test_vm
volumes:
  database:
networks:
  test_vm: